# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://github.com/julia-actions/setup-julia
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 99
    labels:
      - "dependencies"
      - "github-actions"
